apiVersion: v2
name: onecx-portal-iam-kc
version: 0.0.0
appVersion: 0.0.0
description: Onecx Portal IAM for Keycloak
keywords:
  - iam
  - keycloak
sources:
  - https://github.com/onecx/onecx-portal-iam-kc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts

      